#!/bin/bash
#PBS -N gemma2-2b_jb100
#PBS -l select=1:ncpus=8:ngpus=1:mem=40gb
#PBS -l walltime=14:00:00
#PBS -o logs/gemma2-2b_jb100.out
#PBS -e logs/gemma2-2b_jb100.err

# Move to the directory from which job submitted
cd $PBS_O_WORKDIR

echo "$(date "+%Y-%m-%d %H:%M:%S") - gemma2-2b_jb100 started" >> logs/_runtimes.log

# Paths
CONTAINER_PATH="$PBS_O_WORKDIR/containers/mechinterp_cont.sif"
SCRIPT_PATH="$PBS_O_WORKDIR/scripts/inference/gemma2-2b_jb100.py"

# Run the script inside the container
singularity exec --nv \
    -B "$HOME/typo-correct-subspaces:/workspace" \
    -B "/rds/general/user/ifc24/home/typo-correct-subspaces/data:/data" \
    "$CONTAINER_PATH" \
    python "$SCRIPT_PATH" --tensor-parallel

echo "$(date "+%Y-%m-%d %H:%M:%S") - gemma2-2b_jb100 finished" >> logs/_runtimes.log
nvidia-smi --query-gpu=name --format=csv,noheader
