#!/bin/bash
#PBS -N compute_diffs
#PBS -l select=1:ncpus=8:ngpus=1:mem=40gb
#PBS -l walltime=14:00:00
#PBS -o logs/compute_diffs.out
#PBS -e logs/compute_diffs.err

# Move to the directory from which job submitted
cd $PBS_O_WORKDIR

echo "$(date "+%Y-%m-%d %H:%M:%S") - compute_diffs started" >> logs/run_times.log

# Paths
CONTAINER_PATH="$PBS_O_WORKDIR/containers/mechinterp_cont.sif"
SCRIPT_PATH="$PBS_O_WORKDIR/scripts/analyses/1_diffs/compute_diffs.py"

# Run the script inside the container
singularity exec --nv \
    -B "$HOME/typo-correct-subspaces:/workspace" \
    -B "/rds/general/user/ifc24/home/typo-correct-subspaces/data:/data" \
    "$CONTAINER_PATH" \
    python "$SCRIPT_PATH" --tensor-parallel

echo "$(date "+%Y-%m-%d %H:%M:%S") - compute_diffs finished" >> logs/run_times.log
nvidia-smi --query-gpu=name --format=csv,noheader
